// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sVt7u23OBoXQQg59g4rMviwiO-bSQDM',
    appId: '1:572927803857:web:8fa7b78b6ff0acceb460f0',
    messagingSenderId: '572927803857',
    projectId: 'servipop-bd114',
    authDomain: 'servipop-bd114.firebaseapp.com',
    storageBucket: 'servipop-bd114.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUSYU1z4HsGGXdUFeBnKzJuzTm_2I_C_s',
    appId: '1:572927803857:android:c71acc8bf05bf196b460f0',
    messagingSenderId: '572927803857',
    projectId: 'servipop-bd114',
    storageBucket: 'servipop-bd114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1H1U2mOpRG2UXNVWhA_bLWjza_kUb64',
    appId: '1:572927803857:ios:b070176388a25069b460f0',
    messagingSenderId: '572927803857',
    projectId: 'servipop-bd114',
    storageBucket: 'servipop-bd114.firebasestorage.app',
    iosBundleId: 'com.elezdev.servipopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi1H1U2mOpRG2UXNVWhA_bLWjza_kUb64',
    appId: '1:572927803857:ios:b070176388a25069b460f0',
    messagingSenderId: '572927803857',
    projectId: 'servipop-bd114',
    storageBucket: 'servipop-bd114.firebasestorage.app',
    iosBundleId: 'com.elezdev.servipopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6sVt7u23OBoXQQg59g4rMviwiO-bSQDM',
    appId: '1:572927803857:web:d652550a4fc48cb7b460f0',
    messagingSenderId: '572927803857',
    projectId: 'servipop-bd114',
    authDomain: 'servipop-bd114.firebaseapp.com',
    storageBucket: 'servipop-bd114.firebasestorage.app',
  );
}
